services:
  ansible:
    image: ghcr.io/warmattack-lab/ansible-control:251117-1
    container_name: ansible-control
    network_mode: host
    tty: true
    volumes:
      - ./ansible:/workspace
      - ~/.ssh:/root/.ssh:ro
